name: a_la_carte
version: 0.0.1
description: A web server built using the shelf package.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  args: '>=0.10.0 <0.14.0'
  browser: any
  paper_elements: any
  polymer: any
  sass: any
  google_maps: '^2.0.0'
  oauth2: any
  intl: any
  geohash: any
  json_stream_parser: any
  d17:
    git:
      ref: testing
      url: https://github.com/llamadonica/d17.git
  shelf:
    git:
      ref: master
      url: https://github.com/llamadonica/shelf.git
  uuid: any
transformers:
- sass:
    compass: true
    style: compact
- polymer:
    entry_points: web/index.html
- $dart2js:
    $exclude: bin/server.dart
